device: null
#pretrained_model: ckpt/train/2024-08-20_04-34-49_Apf/t[01700]_r[316.39].pt
pretrained_model: null
ckpt_name: LessRewards
seed: 42

# collector
collector:
  total_frames: 2_000_000
  frames_per_batch: 20
  num_envs: 32
  eps_start: 1.0
  eps_end: 0.05
  annealing_frames: 1_200_000
  init_random_frames: 10_000
#  init_random_frames: 0

# buffer
buffer:
  buffer_size: 500_000
  batch_size: 2048

# Optim
optim:
  lr: 1.0e-5
  weight_decay: 0
  max_grad_norm: null

# loss
loss:
  gamma: 0.99
  target_update_polyak: 0.995
  target_entropy_weight: 0.2
  target_entropy: "auto"
  utd_ratio: 1
  loss_function: l2

# logger
logger:
  backend: tensorboard
  model_name: SAC
  exp_name: Train
  test_interval: 50_000
